### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by hack2gather** [Hellsender01/Naughty_Debian#1]
Naughty Debian is not working properly for me.

**Comment by Hellsender01** [comment]
Can you elaborate?

**Comment by hack2gather** [comment]
I have tried the naught _debian it is showing me module error.

**Comment by Hellsender01** [comment]
It is working fine on my side, can you please share screenshots.

**Comment by hack2gather** [comment]
ohk let me take them from my side

**Comment by hack2gather** [comment]
![Screenshot_2022-05-21_06-32-02](https://user-images.githubusercontent.com/97843059/169647704-0d711993-d530-41a0-b3a2-487160d7a857.png)

have a look buddy , maine manually install karne ki koshish ki but nothng happens . ap khud hi dekho kaise kia ho raha hai iss me . requiremnets fle maine manuallay dusra bhu create kar k dekha aur by default walabhi dekha module missing hi bata raha .

**Comment by Hellsender01** [comment]
Have you installed Naughty Debian using `git clone https://github.com/Hellsender01/Naughty_Debian.git`?

**Comment by hack2gather** [comment]
yes

**Comment by Hellsender01** [comment]
Can you please share a screenshot of `ls -R` command inside the Naughty_Debian directory?

**Comment by hack2gather** [comment]
![Screenshot_2022-05-21_07-32-07](https://user-images.githubusercontent.com/97843059/169649807-f5785787-dd87-4e08-99ed-85b3945b3ba0.png)
here it is .....

**Comment by Hellsender01** [comment]
This seems to be an issue at your end, refer to this link for installation steps - https://youtu.be/xuTRFnbcJ64?t=719

**Comment by hack2gather** [comment]
nothing happens abhi bhi same issue hai

**Comment by Hellsender01** [comment]
As I said, This issue is at your end. There is no issue with the code.

**Comment by hack2gather** [comment]
at my end samjha nhi bhai solve kaise karu any idea bhai bcz maine sab try karliya , manual install ka , module install kar k sab nhi ho raha

**Comment by Hellsender01** [comment]
Ok, I can help you troubleshoot, share screenshot of `ls /usr/local/lib/`

**Comment by hack2gather** [comment]
![Screenshot_2022-05-21_08-07-28](https://user-images.githubusercontent.com/97843059/169650836-7a2244f0-decf-403f-b3fd-da2ca2fad24d.png)

yeh raha

**Comment by Hellsender01** [comment]
Inside the Naughty_Debian directory run these commands and comment the screenshot `python3.9 ./naughty_debian.py` and `python3.10 ./naughty_debian.py`

**Comment by hack2gather** [comment]
ntg happen same issue

**Comment by hack2gather** [comment]
i think mujhe manually karna chahiye manually decompile kar k add kar deta hu .deb file me

**Comment by Hellsender01** [comment]
Ok, for now, I am closing this issue, If you have a problem with any other tool then report in the respective repository.
